wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
model:
  desc: null
  value: resnet152
dataset:
  desc: null
  value: cifar10
epochs:
  desc: null
  value: 90
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701936728.764118
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 4
      - 13
      - 16
      - 23
      - 42
      4: 3.8.16
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
